package si.wildplot.gui;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.JComboBox;
import si.wildplot.common.util.IntegrateProperies;
import si.wildplot.core.jocl.BasicCLContext;
import si.wildplot.core.render.Function;

/*
 * (C) Copyright 2013 Vito Čuček.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the GNU Lesser General Public License
 * (LGPL) version 2.1 which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/lgpl-2.1.html
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * @author Vito Čuček <vito.cucek@xlab.si>
 */
public class Operations extends javax.swing.JPanel implements PropertyChangeListener{

	private BasicCLContext clContext;
	private Function currentFunction = null;

    /** Creates new form Operations */
    public Operations(BasicCLContext clContext) {
        this.clContext = clContext;
		initComponents();
		this.integratePanel.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        operationsComboBox = new javax.swing.JComboBox();
        operationsPane = new javax.swing.JLayeredPane();
        integratePanel = new javax.swing.JPanel();
        inteMin = new javax.swing.JTextField();
        inteLabelMin = new javax.swing.JLabel();
        inteLabelMax = new javax.swing.JLabel();
        inteMax = new javax.swing.JTextField();
        inteButtonCalc = new javax.swing.JButton();
        inteComboBoxType = new javax.swing.JComboBox();
        inteSteps = new javax.swing.JTextField();
        inteLabelSteps = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        textOutputScrollPane = new javax.swing.JScrollPane();
        textOutput = new javax.swing.JTextArea();

        setMaximumSize(new java.awt.Dimension(180, 32767));
        setMinimumSize(new java.awt.Dimension(200, 20));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        operationsComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Find zeros", "Integrate", "Derivate" }));
        operationsComboBox.setEnabled(false);
        operationsComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operationsComboBoxActionPerformed(evt);
            }
        });

        operationsPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, operationsComboBox, org.jdesktop.beansbinding.ELProperty.create("${enabled}"), operationsPane, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        integratePanel.setPreferredSize(new java.awt.Dimension(340, 340));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, operationsPane, org.jdesktop.beansbinding.ELProperty.create("${enabled}"), integratePanel, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        inteMin.setText("0.0");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, integratePanel, org.jdesktop.beansbinding.ELProperty.create("${enabled}"), inteMin, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        inteLabelMin.setText("min :");

        inteLabelMax.setText("max :");

        inteMax.setText("1.0");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, integratePanel, org.jdesktop.beansbinding.ELProperty.create("${enabled}"), inteMax, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        inteButtonCalc.setText("calc");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, integratePanel, org.jdesktop.beansbinding.ELProperty.create("${enabled}"), inteButtonCalc, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        inteButtonCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inteButtonCalcActionPerformed(evt);
            }
        });

        inteComboBoxType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Linear interpola...", "Cubic interpola..." }));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, integratePanel, org.jdesktop.beansbinding.ELProperty.create("${enabled}"), inteComboBoxType, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        inteSteps.setText("1.0e-6");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, integratePanel, org.jdesktop.beansbinding.ELProperty.create("${enabled}"), inteSteps, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        inteLabelSteps.setText("steps :");

        javax.swing.GroupLayout integratePanelLayout = new javax.swing.GroupLayout(integratePanel);
        integratePanel.setLayout(integratePanelLayout);
        integratePanelLayout.setHorizontalGroup(
            integratePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(integratePanelLayout.createSequentialGroup()
                .addGroup(integratePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inteLabelMin)
                    .addComponent(inteLabelMax)
                    .addComponent(inteLabelSteps))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(integratePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inteMin, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(inteMax, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(inteSteps, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)))
            .addGroup(integratePanelLayout.createSequentialGroup()
                .addComponent(inteButtonCalc, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(inteComboBoxType, 0, 150, Short.MAX_VALUE)
        );
        integratePanelLayout.setVerticalGroup(
            integratePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, integratePanelLayout.createSequentialGroup()
                .addComponent(inteComboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(integratePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inteLabelMin)
                    .addComponent(inteMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(integratePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inteLabelMax)
                    .addComponent(inteMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(integratePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inteLabelSteps)
                    .addComponent(inteSteps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(inteButtonCalc))
        );

        integratePanel.setBounds(10, 10, 150, 160);
        operationsPane.add(integratePanel, javax.swing.JLayeredPane.MODAL_LAYER);

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("use gpu cores");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, operationsComboBox, org.jdesktop.beansbinding.ELProperty.create("${enabled}"), jCheckBox1, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "output", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(153, 153, 153)));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, operationsComboBox, org.jdesktop.beansbinding.ELProperty.create("${enabled}"), jPanel2, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        textOutputScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        textOutput.setEditable(false);
        textOutput.setBackground(new java.awt.Color(228, 228, 228));
        textOutput.setColumns(20);
        textOutput.setRows(5);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, operationsComboBox, org.jdesktop.beansbinding.ELProperty.create("${enabled}"), textOutput, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        textOutputScrollPane.setViewportView(textOutput);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textOutputScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textOutputScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(operationsComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBox1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(operationsPane, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(238, 238, 238))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(operationsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(operationsPane, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

	private void inteButtonCalcActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_inteButtonCalcActionPerformed
	{//GEN-HEADEREND:event_inteButtonCalcActionPerformed
		if(this.currentFunction != null){
			double min = Double.parseDouble(this.inteMin.getText());
			double max = Double.parseDouble(this.inteMax.getText());
			double step = Double.parseDouble(this.inteSteps.getText());
			int type = 0;
			switch(this.inteComboBoxType.getSelectedIndex()){
				case 0: type = IntegrateProperies.LINEAR; break;
				case 1: type = IntegrateProperies.CUBIC; break;
				case 2: type = IntegrateProperies.MONTE_CARLO; break;
			}
			IntegrateProperies options = new IntegrateProperies(min, max, step, type);
			String out = this.currentFunction.integrate(clContext, options);
			this.textOutput.setText(out);
		}
	}//GEN-LAST:event_inteButtonCalcActionPerformed

	private void operationsComboBoxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_operationsComboBoxActionPerformed
	{//GEN-HEADEREND:event_operationsComboBoxActionPerformed
		String selection = (String)((JComboBox)evt.getSource()).getSelectedItem();
		hideOperations();
		if(selection.compareTo("Integrate") == 0){
			this.integratePanel.setVisible(true);
		}
	}//GEN-LAST:event_operationsComboBoxActionPerformed

	private void hideOperations(){
		this.integratePanel.setVisible(false);
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton inteButtonCalc;
    private javax.swing.JComboBox inteComboBoxType;
    private javax.swing.JLabel inteLabelMax;
    private javax.swing.JLabel inteLabelMin;
    private javax.swing.JLabel inteLabelSteps;
    private javax.swing.JTextField inteMax;
    private javax.swing.JTextField inteMin;
    private javax.swing.JTextField inteSteps;
    private javax.swing.JPanel integratePanel;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox operationsComboBox;
    private javax.swing.JLayeredPane operationsPane;
    private javax.swing.JTextArea textOutput;
    private javax.swing.JScrollPane textOutputScrollPane;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

	public void propertyChange(PropertyChangeEvent evt)
	{
		if(evt.getPropertyName() == "InputField.currentFunction"){
			if(evt.getNewValue() != null){
				Function f = (Function)evt.getNewValue();
				this.currentFunction = f;
				this.operationsComboBox.setEnabled(true);
			}
			else{
				this.operationsComboBox.setEnabled(false);
				this.currentFunction = null;
			}
		}
	}

}
